---
kind: pipeline
name: linux-amd64

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

workspace:
  path: /go/src/github.com/openebs/jiva

steps:
  - name: jiva
    image: golang:1.12
    commands:
      - mkdir -p bin
      - go build  -ldflags "-X main.VERSION=$VERSION" -o bin/longhorn
      - cp bin/longhorn package/longhorn
      - cp bin/longhorn package/jivactl
    environment:
      GO111MODULE: on
      VERSION: 1.7.0

  - name: jiva-image
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile_build_amd64
      context: package
      registry: quay.io
      repo: quay.io/josua-sr/jiva
      tag: 1.7.0-amd64
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password

---
kind: pipeline
name: linux-arm64

clone:
  depth: 1

platform:
  os: linux
  arch: arm64

workspace:
  path: /go/src/github.com/openebs/jiva

steps:
  - name: jiva
    image: golang:1.12
    commands:
      - mkdir -p bin
      - go build  -ldflags "-X main.VERSION=$VERSION" -o bin/longhorn
      - cp bin/longhorn package/longhorn
      - cp bin/longhorn package/jivactl
    environment:
      GO111MODULE: on
      VERSION: 1.7.0

  - name: jiva-image
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile_build_arm64
      context: package
      registry: quay.io
      repo: quay.io/josua-sr/jiva
      tag: 1.7.0-arm64
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password

---
kind: pipeline
name: manifest

clone:
  depth: 1

platform:
  os: linux

steps:
  - name: jiva-image
    image: plugins/manifest
    settings:
      target: quay.io/josua-sr/jiva:1.7.0
      template: quay.io/josua-sr/jiva:1.7.0-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password

depends_on:
- linux-amd64
- linux-arm64
